### ISSUE TITLE
Unmarshal Op.Data to a struct instead of a map

### ISSUE THREAD

**Issue by sfreiberg** [rwynn/gtm#10]
I would like to be able to unmarshal Op.Data into my own struct in the same way that bson does. I could convert the map to a struct myself but that seems error prone. I don't see a way to get access to the raw data to do it myself. Any thoughts?

**Comment by rwynn** [comment]
I will look into adding support in gtm. For now could you use something like https://github.com/mitchellh/mapstructure?

**Comment by sfreiberg** [comment]
Yeah I definitely could do that but like I said I don’t like the idea of having multiple ways to unmarshal data. I think I might just make a fork and stick the raw data in there and unmarshal that with the bson package.

The approach I mention above seems inelegant which is why I opened a ticket instead of a PR. I thought you might have a more elegant approach. I haven’t spent a lot of time looking at the code so if I get the chance and think of an nice way to handle it I’ll post it here.

**Comment by rwynn** [comment]
Took a stab at this in a feature branch.  Seems to work ok while keeping backwards compatibility.  You set a new function in the options under `Unmarshal` that gets passed a namespace and a `bson.Raw`.  Based on that you can unmarshal into whatever struct you want.  Then the result should be in a new field on the op named `Doc`.   Let me know if you notice any problems.

**Comment by sfreiberg** [comment]
Yes that should work for my purposes. Thank you!

**Comment by rwynn** [comment]
No problem. I'd like to get this merged into trunk but I need to make sure I didn't introduce any regressions.  I depend on this project in a couple others.

**Comment by rwynn** [comment]
@sfreiberg this has now been merged into master.  Please let me know if you encounter any problems.
